# Generated by Django 2.2.2 on 2019-06-25 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datasubject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Basis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=250)),
                ('locations', models.CharField(max_length=250)),
                ('user_internal', models.CharField(max_length=250)),
                ('user_pip', models.CharField(max_length=250)),
                ('user_pic', models.CharField(max_length=250)),
                ('policy_use', models.CharField(max_length=500)),
                ('policy_protection', models.CharField(max_length=500)),
                ('policy_backup', models.CharField(max_length=500)),
                ('policy_disposal', models.CharField(max_length=500)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDI.Activity')),
                ('basis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDI.Basis')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDI.Classification')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='act_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDI.ActivityType'),
        ),
    ]
