# Generated by Django 2.2.2 on 2019-07-01 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Activity Types',
            },
        ),
        migrations.CreateModel(
            name='Basis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classifications',
            },
        ),
        migrations.CreateModel(
            name='DataSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Subjects',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('abbr', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250, null=True)),
                ('activity', models.ForeignKey(null=True, on_delete='CASCADE', to='PDI.Activity')),
            ],
            options={
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=250)),
                ('locations', models.CharField(max_length=250)),
                ('user_internal', models.CharField(max_length=250)),
                ('user_pip', models.CharField(max_length=250)),
                ('user_pic', models.CharField(max_length=250)),
                ('policy_use', models.CharField(max_length=500)),
                ('policy_protection', models.CharField(max_length=500)),
                ('policy_backup', models.CharField(max_length=500)),
                ('policy_disposal', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDI.Activity')),
                ('basis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PDI.Basis')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PDI.Classification')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='act_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDI.ActivityType'),
        ),
        migrations.AddField(
            model_name='activity',
            name='data_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PDI.DataSubject'),
        ),
    ]
