# Generated by Django 2.2.2 on 2019-06-27 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PDI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PDI.Activity')),
            ],
        ),
    ]
