# Generated by Django 2.2.2 on 2019-07-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDI', '0002_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='data',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='data',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
